import { mkdirSync, writeFileSync, rmSync, readdirSync, readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
const dir='payload';
const parts=readdirSync(dir).filter(n=>/^c\d+\.txt$/.test(n)).sort();
if(parts.length!==13) throw new Error(`Expected 13 payload chunks, found ${parts.length}`);
const b64=parts.map(n=>readFileSync(`${dir}/${n}`,'utf8')).join('');
const zip=Buffer.from(b64,'base64');
if(zip.length<100000) throw new Error(`Reconstructed archive unexpectedly small: ${zip.length}`);
rmSync('app',{recursive:true,force:true});
mkdirSync('app',{recursive:true});
writeFileSync('source.zip',zip);
execFileSync('unzip',['-t','source.zip'],{stdio:'inherit'});
execFileSync('unzip',['-q','-o','source.zip','-d','app'],{stdio:'inherit'});
console.log('reconstructed',zip.length,'bytes from',parts.length,'chunks');
